name: Code Formatting

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install formatters
      run: |
        pip install black flake8
    - name: Check formatting
      run: |
        black --check .
        flake8 .