name: Flappy Bird RL CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Flappy Bird RL script
      run: |
        python main.py  # Replace this with your entry script, like flappy_dqn.py

    - name: Run unit tests
      run: |
        pip install pytest
        pytest || echo "Tests failed but continuing..."

    - name: Upload model artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/model.pth  # Replace this with your actual model file path
