name: Flappy Bird DQN Training

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup_and_train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install system dependencies
      - name: Install SDL2 and other system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            python3-opengl \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
      
      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      # Install Python dependencies
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt
      
      # Train the model
      - name: Train DQN Agent
        run: python train.py --episodes 5000 --batch_size 32 --lr 0.0001 --gamma 0.99
      
      # Save artifacts
      - name: Upload Model
        uses: actions/upload-artifact@v4
        with:
          name: dqn-model
          path: models/dqn_flappy_bird.pth
      - name: Upload Training Plot
        uses: actions/upload-artifact@v4
        with:
          name: training-plot
          path: results/training_plot.png

  evaluate:
    needs: setup_and_train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Download trained model
      - name: Download Model
        uses: actions/download-artifact@v4
        with:
          name: dqn-model
          path: models/
      
      # Evaluate
      - name: Evaluate Agent
        run: python evaluate.py --model_path models/dqn_flappy_bird.pth --eval_episodes 100
      
      # Save evaluation results
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: |
            results/evaluation_scores.txt
            results/gameplay_recording.mp4
