name: Flappy Bird DQN Training & Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install system dependencies
      - name: Install SDL2 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            python3-opengl \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Install Python packages
        run: |
          pip install -r requirements.txt
      
      - name: Train DQN Agent
        run: python train.py --episodes 3000 --batch_size 32 --lr 0.0001 --gamma 0.99
      
      - name: Save trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/dqn_flappy_bird.pth

  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: models/
      
      - name: Run tests
        run: python test.py --model_path models/dqn_flappy_bird.pth
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test_output/
            test_logs.txt
