name: Flappy Bird DQN Training Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-opengl
          pip install gym pygame numpy torch matplotlib
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  train:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train DQN Agent
        run: python train.py --episodes 5000 --batch_size 32 --lr 0.0001 --gamma 0.99
      - name: Upload Model
        uses: actions/upload-artifact@v3
        with:
          name: dqn-model
          path: models/dqn_flappy_bird.pth
      - name: Upload Training Plot
        uses: actions/upload-artifact@v3
        with:
          name: training-plot
          path: results/training_plot.png

  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Download Model
        uses: actions/download-artifact@v3
        with:
          name: dqn-model
          path: models/
      - name: Evaluate Agent
        run: python evaluate.py --model_path models/dqn_flappy_bird.pth --eval_episodes 100
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: evaluation-results
          path: |
            results/evaluation_scores.txt
            results/gameplay_recording.mp4
