name: Train Flappy Bird DQN

on: [push, pull_request]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install system dependencies
      - name: Install SDL2 and Python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            python3-opengl \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install Python packages
      - name: Install requirements
        run: |
          pip install gym==0.26.2 pygame==2.1.3 numpy torch matplotlib

      # Create necessary directories
      - name: Setup directories
        run: mkdir -p models figures

      # Run training
      - name: Train the agent
        run: |
          python -c "
          import os
          os.makedirs('models', exist_ok=True)
          os.makedirs('figures', exist_ok=True)
          from train import DQNAgent
          agent = DQNAgent(state_size=8, action_size=2)
          agent.train(episodes=3000)
          "

      # Upload results
      - name: Save trained model
        uses: actions/upload-artifact@v4
        with:
          name: flappy-model
          path: models/
          
      - name: Save training plots
        uses: actions/upload-artifact@v4
        with:
          name: training-figures
          path: figures/
